# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 670b42d99b4052f52e1f76674a59e552373adbe560745ae4e929106f48c1d82d6fb8aab4adf1705fbe777b3b0f7d6fd12d5b6013176c203aded287aef4c598be

test:
  secret_key_base: da52de6a07545aadc274b2cc15c44882f04d83c40642d55ac002786ece4fbd9cdb0c4f0aaa605c533953ec17ac6c305bbd1022c169d08d6d3c6a8eb3ddc5b552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
