# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d0c9cbd610f619b7323077ca01c767a026eccb169e6d8b6d576a99f209bc2b3c887a3f9d4727dbce405f11e66756e5fbafdcc160a3f2c665b7698ebe8f1f6b

test:
  secret_key_base: 8a796428fa54fd0401e9a2bc44b578a152da42453598f2ca7290c84dfa045ccad4dd88b96c46b37755dee553e273edca6c4894db834e2ed2741f9c7a48e495d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
