# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3edebac2a977dca081dd3bc52c8ca2a3b21b8b5bb7b2ab5c0bcd924a7fb44671b8b6bf850db10c0c1bc9bf4c5ca7d1d07df40f6ba23cceff9ac7ef33b76b7a4c

test:
  secret_key_base: 8e8dd85aa0de65e175fa34a2057f2b3e25d7fca64e286bed9256894cd19681102d6fd1bf2281b0b5ade9df34f3a03e33b136daed9a41b4b5cfb23d90ba4eca37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
